// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzolmxnsimxkpaumkhbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6b2xteG5zaW14a3BhdW1raGJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDY2MTcsImV4cCI6MjA2MzQyMjYxN30.Jr_A1f0-MlXE_ql1WDItzsqtDCZnXcwEO9cPsJMYSG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);